# Generated by Django 5.1.4 on 2025-01-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('LecturerID', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=255)),
                ('Username', models.CharField(editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=255)),
                ('Username', models.CharField(editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ClassID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=100)),
                ('LecturerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('GradeID', models.AutoField(primary_key=True, serialize=False)),
                ('FinalGrade', models.CharField(blank=True, max_length=10, null=True)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.class')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('AttendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('AttendanceStatus', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=8)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.class')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
            ],
        ),
    ]
