# Generated by Django 5.1.4 on 2025-01-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='Time',
            field=models.TimeField(default='08:30:00'),
            preserve_default=False,
        ),
    ]
