# Generated by Django 5.1.4 on 2025-01-05 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_attendancerecord_attendancestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='ClassID',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='StudentID',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='ClassID',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='StudentID',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='AttendanceStatus',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=8),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('EnrollmentID', models.AutoField(primary_key=True, serialize=False)),
                ('EnrollmentDate', models.DateField(auto_now_add=True)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.class')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='EnrollmentID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.enrollment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='EnrollmentID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.enrollment'),
            preserve_default=False,
        ),
    ]
