# Generated by Django 5.1.4 on 2025-01-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_attendancerecord_classid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='SessionNumber',
            field=models.IntegerField(default=0),
        ),
    ]
